### ISSUE TITLE
Stitching is broken on Windows

### ISSUE THREAD

**Issue by JonnyBurger** [JonnyBurger/remotion#101]
As reported on Discord:

![image](https://user-images.githubusercontent.com/1629785/107950725-70507d00-6f97-11eb-9bd4-b5245a052c38.jpeg)

**Comment by ant-hnikolov** [comment]
Hi @JonnyBurger, I'm still getting this issue on the latest branch :(

**Comment by JonnyBurger** [comment]
Good point, need to upgrade Spotify Wrapped example 👍

**Comment by JonnyBurger** [comment]
@ant-hnikolov The project should now use the newest Remotion version and therefore work on Windows!

**Comment by ant-hnikolov** [comment]
@JonnyBurger hahah I'm not sure how updating an unrelated example fixed my issue, but thanks for whatever magic you did, it worked!!
