### ISSUE TITLE
Supplying string to <Img/> src causes screenshots issues on render

### ISSUE THREAD

**Issue by joshlatimer** [JonnyBurger/remotion#107]
Amazing project, thank you :)

I've just been stuck for an hour as I stupidly changed all my <img/> tags to remotion's <Img/> tag but I only changed the src to use requires for some of them. When I rendered the project I was getting the error 
`Error taking screenshot TimeoutError: waiting for function failed: timeout 30000ms exceeded`

It seems that if you stupidly supply a traditional string path to <Img/> for example `<Img src=" logo.png "/>` then you'll receive the above error on rendering. It would be amazing if automatic detection is added for this to suggest using require instead

**Comment by Iamshankhadeep** [comment]
you can just pass `<Img src={require('./logo.png')}>` it will solve the issue.
