### ISSUE TITLE
Rendering artifact in WebM

### ISSUE THREAD

**Issue by JonnyBurger** [JonnyBurger/remotion#111]
Can be reproduced here:

https://github.com/JonnyBurger/youtube-likes-recap-video-maker/commit/7b15213f7287dd6770de37685526b72864331a88

Should send a PR once the issue is fixed

**Comment by pierreminiggio** [comment]
Confirming on that on this repo https://github.com/pierreminiggio/youtube-likes-recap-video-maker/commit/ac60775fd0bed16596dcb5846127fa0ef96b520a I see no artefact at concurrency = 1 and 2
I start noticing artefacts at concurrency = 4
