### ISSUE TITLE
Sequence wraps component in AbsoluteFill

### ISSUE THREAD

**Issue by jacobp100** [JonnyBurger/remotion#112]
I'm not sure I get the logic behind sequences changing the layout.

For example, I wanted to make a component that staggers its children, each in its own sequence. Then each child can have its own entrance animation.

```tsx
import React from 'react';
import {Sequence} from 'remotion';

export default ({
	staggerInFrames = 0,
	durationInFrames = Infinity,
	children = [<></>],
}) => {
	return (
		<>
			{React.Children.map(children, (child, i) => (
				<Sequence
					from={i * staggerInFrames}
					durationInFrames={durationInFrames - i * staggerInFrames}
					name={`Stagger-${i + 1}`}
				>
					{child}
				</Sequence>
			))}
		</>
	);
};
```

**Comment by JonnyBurger** [comment]
This is a fair point. I think often times it turns out useful, but it is very opinionated and in your case it's undesired.

Backwards-compatibility is a headache here, probably have to add a new prop to control the behavior.
Moving this to the roadmap!
