### ISSUE TITLE
What happens if you forget to set "durationInFrames" in Sequence

### ISSUE THREAD

**Issue by pierreminiggio** [JonnyBurger/remotion#113]
If I ever forget to set "durationInFrames" prop for my Sequence (and It did happen :D), the video preview and rendering will play just fine, but the timeline will look weird (the clips won't be stretched and will be look far apart from one another).
I think it should throw an exception in my face to remind my dumb ass to set it.
![image](https://user-images.githubusercontent.com/35456349/108136303-1f857500-70ba-11eb-8383-2d0a5b914a27.png)
![image](https://user-images.githubusercontent.com/35456349/108136344-30ce8180-70ba-11eb-90c3-bb6774cde657.png)

If you wanna reproduce : clone and checkout to this commit https://github.com/pierreminiggio/youtube-likes-recap-video-maker/blob/3351e845813145cd14dc2cb9f1664bf291d67781/src/Hello.tsx
And comment the durationInFrames line

**Comment by JonnyBurger** [comment]
Good idea! Especially now that we support plain JS, those people don't even have the type error! Let's throw an error if it happens.

**Comment by JonnyBurger** [comment]
This is now an error and will be released in 1.4.0 :party
