### ISSUE TITLE
useVIdeoConfig sometimes returns null 

### ISSUE THREAD

**Issue by yun8boo** [JonnyBurger/remotion#123]
Looking at the type of useVIdeoConfig, it is a type that return () => VideoConfig, but sometimes it return null

code
<img width="528" alt="スクリーンショット 2021-02-19 17 48 29" src="https://user-images.githubusercontent.com/32152877/108481186-3656e200-72db-11eb-9701-a6faf9040fa7.png">

log
<img width="721" alt="スクリーンショット 2021-02-19 17 49 11" src="https://user-images.githubusercontent.com/32152877/108481206-3d7df000-72db-11eb-9a6a-7f8fcd1f8023.png">

**Comment by JonnyBurger** [comment]
Good point! Are you calling it outside a composition? Should probably be an error I agree!
