### ISSUE TITLE
Windows support

### ISSUE THREAD

**Issue by StefanWerW** [JonnyBurger/remotion#13]
I am having some problems running the `npx create-video` command on windows.

'mv' is not recognized as an internal or external command, operable program or batch file.

![image](https://user-images.githubusercontent.com/12717998/107282101-d6e70f80-6a5a-11eb-941d-cb36ed8ebe25.png)

Could we use some universal strategy? Maybe the [mv](https://www.npmjs.com/package/mv), [cp](https://www.npmjs.com/package/cp) and [rimraf](https://www.npmjs.com/package/rimraf) packages.

Thanks, nice project!

**Comment by kacemws** [comment]
Hey, ran through the same problem, the issue is that mv is a unix command, so to overcome this, i opened git bash then executed yarn create video ( or npx create-video)
good luck !

**Comment by JonnyBurger** [comment]
Thanks for reporting!
Windows support at the moment is not really good right now. I plan on installing Windows to be able to test Remotion in the near future!
In the meanwhile, I opened #15 to fix the issue you mentioned 👍

**Comment by filiptronicek** [comment]
@JonnyBurger would it be possible to include a Docker image to support Windows? I think it would be easier to also execute on some Linux systems.

**Comment by JonnyBurger** [comment]
@filiptronicek This could be a solution, but I guess what makes it hard is that when you change your code, one would have to rebuild the docker image? Which would make Fast Refresh very slow?

Would consider this if someone has expertise on how to achieve it.

**Comment by jalajcodes** [comment]
@JonnyBurger I think it's possible to make live reload work using docker volumes

**Comment by filiptronicek** [comment]
We could start a nodemon instance in Docker, right? Maybe nodemon won't be the best thing for this, but something of this nature.

**Comment by JonnyBurger** [comment]
Would be worth considering, although I am thinking the nicest solution would be to just add native Windows support, and also the easiest, what do you think? Any other benefits of using inside Docker?

**Comment by filiptronicek** [comment]
I think using Docker would improve some workflows just because of how easily deployable it is. No downloads and installs, just one simple command. @JonnyBurger

**Comment by JonnyBurger** [comment]
I agree, would be nice. There is already a Dockerfile included for SSR, but we would need one for development as well. Do you want to create a separate issue for it?

On the Windows side, I got Parallels and a Windows license now, soon I'll be able to properly test on Windows!

**Comment by filiptronicek** [comment]
I can make it into a separate issue, sure, @JonnyBurger!

**Comment by JonnyBurger** [comment]
Windows support will be available in the next release!
