### ISSUE TITLE
Audio Support Quest

### ISSUE THREAD

**Issue by RohovDmytro** [JonnyBurger/remotion#138]
While having a great plans for this lib, the lack of audio support is a big thing for me.

@JonnyBurger, can you share the biggest issues and challenges with audio support? Or any ETA about this. Maybe share the roadmap of this issue or is there is anything people could help.

**Comment by JonnyBurger** [comment]
Experimental Audio support has been submitted as a PR! https://github.com/JonnyBurger/remotion/pull/128

The roadmap is basically to make some bugfixes and then ship it as v1.4 this week. After that, I'll review the audio PR, make some changes if necessary and write docs, soo hopefully it will ship soon!

If you can't wait, you can even clone it and try the PR out today, feedback on it would be awesome!

Hope that answers your question and that I can close the issue 😊
