### ISSUE TITLE
use vite/esbuild

### ISSUE THREAD

**Issue by sakthisaran65** [JonnyBurger/remotion#149]
would help improve hmr speed and rendering speed..

**Comment by JonnyBurger** [comment]
I am a big supporter of that!
I even [made a video](https://twitter.com/JNYBGR/status/1274386531096989696) about this topic before 😁 

It might be not very easy and urgent, but I definitely want to explore this.

**Comment by JonnyBurger** [comment]
Vite doesn't yet have support for fast refresh, so I would say it's a nogo.
ESBuild bundler doesn't even have a watch mode.

We are too early for it, but in the next release we are going to take a step into the right direction: Transpile code using ESBuild, bundling using Webpack!

This already speeds it up significantly, if a bundler shows up that is really good and fulfills our needs, I think we are happy to consider using it in Remotion!

**Comment by nandorojo** [comment]
@JonnyBurger is there a way to transpile certain packages from `node_modules`, similar to `next-transpile-modules`? I'm seeing this error when I try to use a `react-native` package. 

![image](https://user-images.githubusercontent.com/13172299/132146511-3b50e62d-f7c8-4c44-92b8-50f322268127.png)

I tried adding a custom `babel-loader` into webpack. Here's my `remotion.config.ts` file 

```ts
import { Config } from 'remotion'

Config.Rendering.setImageFormat('png')
Config.Output.setOverwriteOutput(true)
Config.Bundling.overrideWebpackConfig((config) => {
  return {
    ...config,
    resolve: {
      ...config.resolve,
      alias: {
        ...config.resolve?.alias,
        'react-native$': 'react-native-web',
      },
    },
    module: {
      ...config.module,
      rules: [
        ...(config.module?.rules || []),
        {
          test: /\/node_modules\/(dripsy|@dripsy)\/.*\.js$/,
          loader: 'babel-loader',
        },
      ],
    },
  }
})
```

but then I get this...

<img width="956" alt="Screen Shot 2021-09-05 at 8 50 06 PM" src="https://user-images.githubusercontent.com/13172299/132146534-2fd01af0-24e9-436f-af60-145e2514c208.png">

I'm a bit too used to the world of Next.js / Expo where I never touch Babel or webpack files, so I'm not totally sure what to make of it.

**Comment by nandorojo** [comment]
Ignore my previous message, I solved it by adding `'@babel/plugin-transform-react-jsx'`. Here's my new remotion config:

```ts
import { Config } from 'remotion'

Config.Rendering.setImageFormat('png')
Config.Output.setOverwriteOutput(true)
Config.Bundling.overrideWebpackConfig((config) => {
  return {
    ...config,
    resolve: {
      ...config.resolve,
      alias: {
        ...config.resolve?.alias,
        'react-native$': 'react-native-web',
      },
    },
    module: {
      ...config.module,
      rules: [
        ...(config.module?.rules || []),
        {
          test: /\/node_modules\/(dripsy|@dripsy)\/.*\.js$/,
          loader: 'babel-loader',
          options: {
            plugins: ['@babel/plugin-transform-react-jsx'],
          },
        },
      ],
    },
  }
})
```
