### ISSUE TITLE
Video is jumpy when exported with concurrency > 1

### ISSUE THREAD

**Issue by somebody32** [JonnyBurger/remotion#159]
Following up our discussion in https://github.com/JonnyBurger/remotion/issues/135

I've found out that when I'm using React's state to create an animation and exporting with concurrency > 1 (4 by default on my machine) I'm getting a jumpy output.

**What I'm trying to achieve (export with concurrency = 1)**

https://user-images.githubusercontent.com/25742/109627155-9e11f600-7b41-11eb-8091-fa0bf40e32f2.mp4

**What I'm getting when default concurrency is used**

https://user-images.githubusercontent.com/25742/109627243-b3872000-7b41-11eb-943b-3e4dd1484c63.mp4

**Code of the counter**

```tsx
function SegmentInfo({title, value, prevValue}) {
  let [text, setText] = useState<string>(prevValue);
  let frame = useCurrentFrame();
  let framesToSwitch = 2;
  let lastChange = useRef(framesToSwitch);

  useEffect(() => {
    if (value === prevValue) {
      return;
    }

    if (text === String(value)) {
      return;
    }

    if (lastChange.current < framesToSwitch) {
      lastChange.current += 1;
      return;
    }

    let valuesToCover = Math.abs(prevValue - value);
    let goingUp = value > prevValue;

    
    let step = 1;
    if (valuesToCover >= 20 && Math.abs(+text - value) >= 2) {
      step = 2;
    }

    setText((s) => (goingUp ? String(+s + step) : String(+s - step)));
    lastChange.current = 0;
  }, [frame]);
...
```

As soon as I'm basing state updates on the previous value, I assume that could be the problem with concurrency.

**Remotion version 1.4.1**

**Comment by JonnyBurger** [comment]
Hi @somebody32! Thanks for posting the example.

This is somwhat expected, and I think you have already realized yourself what is going on.
The problem is that frames rely on the state of other frames, ideally every frame is independent.

But I think you can solve the problem without too much effort!

I would define an array with percentages

```tsx
const values = [0, 25, 36, 30]
```

And then calculate the steps inbetween.

```tsx
const frame = useCurrentFrame();
const {durationInFrames} = useVideoConfig()

const progress = (frame + 1) / durationInFrames
const lowerIndex = Math.floor(progress)
const upperIndex = Math.ceil(progress)
const inbetweenProgress = progress % 1;

const value = interpolate(inbetweenProgress, [0, 1], [values[lowerIndex], values[upperIndex]])
```

This will animate from 0 to 25 to 36 to 30. You will need pauses inbetween, which I didn't implement yet but hope it gets you started!

I don't wanna change something in Remotion because something that multithreaded rendering is too sweet!
Hope this helps! 😊

**Comment by somebody32** [comment]
@thanks @JonnyBurger! I think the main source of confusion was that everything was working perfectly inside the browser but then broken in the export. But I agree that it is a more userland problem, and the only "solution" to it could be a mention in the docs

**Comment by JonnyBurger** [comment]
@somebody32 +1 on that, planning to write some documentation about that! Created an issue https://github.com/JonnyBurger/remotion/issues/160

**Comment by Aloysb** [comment]
@somebody32 How do you set the concurrency to 1 ?
