### ISSUE TITLE
Interpolate with arrays of any size

### ISSUE THREAD

**Issue by slorber** [JonnyBurger/remotion#164]
As I'm used to RN, I wanted to do something like:

```js
	const opacity = interpolate(
		frame,
		[0, intro , intro + main, intro + main + outro],
		[0, 1, 1, 0],
	);
```

Unfortunately, only arrays of 2 are supported  for now.

This is not very convenient as we  need to create multiple smaller interpolations to obtain the final result you want.

I'm using something like `const opacity = Math.min(opacityIntro, opacityOutro);`

**Comment by JonnyBurger** [comment]
Totally with you on this one! Also mentioned it on #145 though it's not exactly the same.
Looking forward to implement this soon.

**Comment by slorber** [comment]
🙏
