### ISSUE TITLE
Can't stop video playing

### ISSUE THREAD

**Issue by sashee** [JonnyBurger/remotion#165]
I've just updated to 1.5.0 and I noticed that if I start the video playback either with the space key or the play button under the video I can's stop it anymore. I click on the pause button and that changes state, but the video is still playing.

**Comment by JonnyBurger** [comment]
Thanks for the report - you are referring to using the <Video> component?

**Comment by sashee** [comment]
I start the server with ```npm start``` then open the localhost:3000 in a browser. Then I see the timeline, the video, and the controls below the video. I use the play button to start playback, and can't stop it anymore

**Comment by sashee** [comment]
It's strange, I've tried again and it's working now. Seems like it's not happening every time.

I'll investigate a bit more and let you know if I can figure out when this issue happens

**Comment by JonnyBurger** [comment]
@sashee got it thanks! I think i know what it is, bugfix release hopefully coming later today 🙂 from what i can tell it happens only every so often fortunately

**Comment by sashee** [comment]
Great:) It seems like it's happening more often when the playback framerate is low, but it's only a hunch.

**Comment by JonnyBurger** [comment]
@sashee Should be resolved by upgrading. Run `npm run upgrade`, you should get

```
+ @remotion/cli@1.5.1
```
If not it's still rolling out. I think this fixes it, but it not, comment here I'll reopen it!

**Comment by sashee** [comment]
Thanks! I'll check it later.
