### ISSUE TITLE
Video of dynamic duration, 

### ISSUE THREAD

**Issue by slorber** [JonnyBurger/remotion#166]
I'd like to generate a video based on dynamic data.

It was not very clear to me how to fetch  that data before rendering the composition, so that I can compute the duration in frames.

```
const RemotionVideo: React.FC = () => {
  const items = useItems() ?? [];
  const frames = items.length * FramesPerItem;
  return (
    <>
      <Composition
        id="Items"
        component={ItemsComposition}
        durationInFrames={frames}
        fps={30}
        width={1920}
        height={1080}
        defaultProps={{items}}
      />
    </>
  );
};
```

I tried to render null, or play with delay/continue in the hook but it didn't really work

I'd like to fetch all the data I'll need ahead of time before even starting to render the video, instead of lazy loading the data. Is that possible? Can we fetch the data before rendering the composition?

**Comment by JonnyBurger** [comment]
Yes since 1.4.0 it's possible using `delayRender` and `continueRender`.

```tsx
const RemotionVideo: React.FC = () => {
  const [duration, setDuration] = useState<number | null>(null)
  const handle = useState(() => delayRender());

  useEffect(() => {
    fetchDurationSomehow()
    .then(() => {
      setDuration(duration);
      continueRender(handle)
    })
  }, []);


  const items = useItems() ?? [];
  const frames = items.length * FramesPerItem;


  if (duration === null) {
  	return null;
  }
  return (
    <>
      <Composition
        id="Items"
        component={ItemsComposition}
        durationInFrames={duration}
        fps={30}
        width={1920}
        height={1080}
        defaultProps={{items}}
      />
    </>
  );
};
```

*Caveat*: It's not yet possible to determine the duration based on the `--props` that you pass in on the CLI because they will be undefined at this stage. Planning to make this possible but it requires a breaking change. So this will be the goal for 2.0, whatever and whenever that means.

So leaving this open, also as a reminder that this needs better documentation.

**Comment by slorber** [comment]
Thanks, will try to do that!

**Comment by codergautam** [comment]
One thing I like to do is have seperate files that fetch data and store into a JSON or txt file, and graphic data into the public folder, and run a cli command that will read those files and make the video

**Comment by JonnyBurger** [comment]
@codergautam You can read files from the public directory using `getStaticFiles()`: https://www.remotion.dev/docs/getstaticfiles

For calculating the duration based on these files, we have big upgrades coming next monday: https://v4.remotion.dev/docs/data-fetching

**Comment by JonnyBurger** [comment]
2023 best practice for dynamic duration: https://www.remotion.dev/docs/dynamic-metadata

**Comment by codergautam** [comment]
Thanks!
