### ISSUE TITLE
License is not permissive

### ISSUE THREAD

**Issue by zapplebee** [JonnyBurger/remotion#17]
The license field in package.json is UNLICENSED

[package.json | npm Docs](https://docs.npmjs.com/cli/v6/configuring-npm/package-json)

> Finally, if you do not wish to grant others the right to use a private or unpublished package under any terms:

**Comment by zapplebee** [comment]
To be clear, I have read the license file, but is there a more appropriate package.json value to represent a custom license?

**Comment by JonnyBurger** [comment]
Good point, in the root package.json I put `SEE LICENSE IN LICENSE.md` which is valid SPDX.
I'm gonna put it in each package.json 👍

**Comment by JonnyBurger** [comment]
Hopefully solved by https://github.com/JonnyBurger/remotion/pull/18, gonna be in the next release, which is gonna be soon!
