### ISSUE TITLE
How to set duration in frame of Composition dinamically?

### ISSUE THREAD

**Issue by FelippeChemello** [JonnyBurger/remotion#196]
I would like to set durationInFrame of Composition dinamically.

I thinked about using fetch in Video.tsx, however for this I will need to receive in props an Id to search this data in my API. At the moment I can't find any solution for receiving data with props on root component, is there any solutions?

I have already forked remotion and I am trying to implement something like this, but it looks like userProps cannot be accessible at root component.

I have made something like this in renderEntry.tsx
```
  const userProps = getUserProps ();
  console.log (userProps);
  
  render (
    <Internals.RemotionRoot>
      <Root {... userProps} />
      <GetVideo />
    </Internals.RemotionRoot>,
    document.getElementById ('container')
  );
```
However looks like userProps is passing blank.

**Comment by FelippeChemello** [comment]
After some work on it, I realized that I was not getting userProps because it was stucking at `getCompositions`. 

This method check whats compositions are correctly configured and allowed to render, however I was passing a prop to the composition and at this moment it wasn't passing the props to this validation, so I made it because it was needed for my case use. 

What do you think about it @JonnyBurger? Do you think about any problem at passing userProps at getting compositions?

**Comment by JonnyBurger** [comment]
Hey @FelippeChemello! Thanks a lot for bringing it up and yes I am 💯 % on you with this, I also mentioned it in #185 that I want to do this for Remotion 2.0 (it's a breaking change since we change the function signature of `getCompositions`). The fact that you sent a PR will only speed up the release of 2.0, so thank you very much! I'll take a look soon 🙌
