### ISSUE TITLE
[Feature request/question] Table of contents supported

### ISSUE THREAD

**Issue by jmarlena** [JonnyBurger/remotion#216]
Hello! 

I'm just wondering if this project supports a table of contents so viewers can more easily navigate the video's contents. 

Thanks for your time. 💛

**Comment by JonnyBurger** [comment]
Hey @jmarlena! 
Interesting question. As far as I know there is no way to include a table of content in the MP4 format, which is the format of the end artifact. This would be more player specific (like the YouTube feature where you can jump to chapters).

But I am interested to hear what sort of thing you are trying to build. Maybe I can give a more specific input on it.

**Comment by jmarlena** [comment]
I want a way to show a table of contents next to the video like from this egghead.io course:  https://egghead.io/lessons/javascript-introduction-to-github

![image](https://user-images.githubusercontent.com/6732600/113034785-5fbf2500-9147-11eb-9857-d4856e09793e.png)
