### ISSUE TITLE
just wondering how you render react components to images?

### ISSUE THREAD

**Issue by rainy-25Ghz** [JonnyBurger/remotion#22]
do u use SSR render react to html then convert html to image by puppeteer?

**Comment by JonnyBurger** [comment]
You are wondering how it works technically right?

Yes, it takes screenshots using puppeteer. You could take a look at the source code: https://github.com/JonnyBurger/remotion/blob/c845c3937bed33468f9f788dbdc6967d665a40f3/packages/renderer/src/render.ts#L6

I'm closing this as there doesn't seem be something actionable remaining.
