### ISSUE TITLE
Static images

### ISSUE THREAD

**Issue by nandorojo** [JonnyBurger/remotion#226]
Hey @JonnyBurger, incredible work here.

Is there a way to use Remotion to generate an image, instead of a video? I assume this would just be a single frame, exported as a JPG/PNG, but I wonder what you think the best way is. Thanks so much!

**Comment by Iamshankhadeep** [comment]
hey @nandorojo we do have a way to generate a single image or multiple image in a range.
You have to use `--image-format` `--sequence` and `--frames`. if you pass a single frame number in `--frames=10` in cli then remotion will generate the 11th(10+1) frame.

More about cli options [here](https://www.remotion.dev/docs/cli)

Hope it helps.

**Comment by nandorojo** [comment]
Thank you!

**Comment by JonnyBurger** [comment]
Thanks @Iamshankhadeep a small note, this is only on `main` branch and not yet in the `1.5.3` release on NPM. You can either make a composition with duration of 1 frame and use `--sequence` to export it, or if you are feeling  dangerous, use the prerelease of V2 (update all Remotion packages to 1.6.0-alpha.74db7d81).

BTW great work with Moti! I might try it out soon too 🙂

**Comment by nandorojo** [comment]
Got it, good to know. I'm still in my exploration phase with Remotion so I don't mind playing with the unreleased features. This thing is really cool, I'm impressed.

And thanks! I'd love for you to try it. Let me know if you have any questions.
