### ISSUE TITLE
Add config to set speed for the <Video> element

### ISSUE THREAD

**Issue by sashee** [JonnyBurger/remotion#232]
The ```playbackRate``` allows setting the video playback speed, but unfortunately it is not available as an attribute. Because of this there is no way to change the speed of embedded videos.

It would be a nice feature to add a ```speed``` property to the ```<Video>``` element. For development, it could set the ```playbackRate``` via code (see [this example](http://daniemon.com/tech/html5/playbackRate/)), and in rendering the current frame calculation could take this setting into account.

**Comment by JonnyBurger** [comment]
+1, this would indeed a very useful functionality! Adding to backlog and hope we get to it not too far in the future! ✌️
