### ISSUE TITLE
Make the preview server's port configurable

### ISSUE THREAD

**Issue by sashee** [JonnyBurger/remotion#234]
[<img alt="Issuehunt badges" src="https://img.shields.io/badge/IssueHunt-%2450%20Funded-%2300A156.svg" />](https://issuehunt.io/r/JonnyBurger/remotion/issues/234)

Currently, the preview server chooses a port between 3000 and 3100 ([ref](https://github.com/JonnyBurger/remotion/blob/main/packages/bundler/src/index.ts#L67)). I use an express http proxy to make the preview page available and I can proxy to any port.

The startServer occupies the "precious" 3000 port and it offers no configuration over this. It would be nice to have an optional port parameter and the express server would use that instead of finding a free port for itself.

---

<details>
<summary>
<b>IssueHunt Summary</b>
</summary>

### Backers (Total: $50.00)

- [<img src='https://avatars.githubusercontent.com/u/1629785?v=4' alt='jonnyburger' width=24 height=24> jonnyburger](https://issuehunt.io/u/jonnyburger) ($50.00)

### Tips

- Checkout the [Issuehunt explorer](https://issuehunt.io/r/JonnyBurger/remotion/) to discover more funded issues.
- Need some help from other developers? [Add your repositories](https://issuehunt.io/r/new) on IssueHunt to raise funds.
</details>

**Comment by JonnyBurger** [comment]
It's not a big priority for me (I don't understand why it's a problem that it uses 3000 or a higher one if available, maybe you can elaborate more on it), but I am happy to put it in the "backlog" and if someone wants this functionality fast, accept a contribution for it!

**Comment by sashee** [comment]
It's only a minor inconvenience for me, just wanted to document it somewhere.

I start the preview server like this:

```
const app = require('express')();
app.use('/audiogen', proxy(`http://localhost:${audioGenPort}`));

process.env.AUDIOGEN_URL = "/audiogen";

loadConfigFile(getConfigFileName());

const port = await startServer(
  "@remotion/cli/dist/previewEntry.js",
  entryPoint,
);
app.use('/', proxy(`http://localhost:${port}`));
app.listen(8080);
```

I start other services and other ports and wire them to paths with express proxy. In effect, it allows me to call something like ```/audiogen``` and it will be routed to a separate service.

But as the preview server takes the 3000 port (and the main express the 8080), if I later start something on port 3000 it will fail. Even though I don't need to reach the preview server directly.

But again, it's just a minor issue.

**Comment by JonnyBurger** [comment]
@sashee Makes sense to me! I'll add it to the roadmap and intend to implement it.

**Comment by JonnyBurger** [comment]
I am adding a bounty that gets paid to whoever would like to implement the feature - requirements: should be able to specify this option via CLI, config file and to `renderFrames()` API.

Also should be mentioned in the SSR docs page, the CLI options doc page and the config file docs page.

Should validate that the port is a valid number and if this option is passed but the port is busy, it should throw an error.

**Comment by mikaoelitiana** [comment]
Hi all. I want to give this issue a try

**Comment by JonnyBurger** [comment]
@mikaoelitiana Thats awesome, thanks for letting us know! 🥳

**Comment by mikaoelitiana** [comment]
@JonnyBurger @sashee for the CLI part, I have been able to handle it. But for the `renderFrames` API, I am not sure to understand what I should add?

**Comment by sashee** [comment]
@mikaoelitiana , I think that should be the ```startServer``` API.
