### ISSUE TITLE
Weird Webpack dynamic imports

### ISSUE THREAD

**Issue by JonnyBurger** [JonnyBurger/remotion#235]
![image](https://user-images.githubusercontent.com/1629785/114610960-c80e1a80-9ca0-11eb-85fd-d5d03c773ae7.png)

**Comment by romannotroman** [comment]
Ran also into this issue. After changing: 
`const imgs = images.map((i) => require( "i"));`
to
`const imgs = images.map((i) => require( "../assets/" + i));`
A new error emmerged:

`Module parse failed: Unexpected character '' (1:4)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders`
