### ISSUE TITLE
should persist 100% / 50% / fit option

### ISSUE THREAD

**Issue by JonnyBurger** [JonnyBurger/remotion#239]
In Preview Editor, currently this setting gets reset on every reload

**Comment by Tobijudah** [comment]
After reload, do you mean hot-refresh or the user manually re-loading the page?

**Comment by JonnyBurger** [comment]
@Tobijudah Thanks for your interest in this issue! 🙌 

I mean after reloading the page, so it should work similar to other options such as the transparency toggle / rich timeline toggle where it just saves the option to local storage.

**Comment by Tobijudah** [comment]
Alright. On it

**Comment by JonnyBurger** [comment]
Solved by #289
