### ISSUE TITLE
Using javascript frameworks with Remotion

### ISSUE THREAD

**Issue by steakscience** [JonnyBurger/remotion#24]
How trivial would it be to, for example, start using d3.js (data visualization) with this?

The potential for Remotion is actually incredible

**Comment by JonnyBurger** [comment]
Hey @steakscience! I'm pretty sure D3 will just work if you install it with NPM in your project. Give it a try! :)

Should there be struggles, glad to help!

**Comment by JonnyBurger** [comment]
I'm closing it as there is nothing actionable here, feel free to ask if something comes up!
