### ISSUE TITLE
Put `yarn create video` on homepage

### ISSUE THREAD

**Issue by JonnyBurger** [JonnyBurger/remotion#266]
Just like many other projects, put the get started command right on the website and not hide it in the docs section

**Comment by Tobijudah** [comment]
Hey Jonny. Wanting to hop on this! Any ideas on how you want it to be on the homepage? Or I should try some and you decide which is best?

**Comment by JonnyBurger** [comment]
Hey @Tobijudah! Thanks a lot for this! 😊 
I am open to it, I think it can be pretty simple! Here are a few ones I personally like:

![image](https://user-images.githubusercontent.com/1629785/115158464-86111a00-a08e-11eb-9a2b-63b95bb6ed0a.png)


![image](https://user-images.githubusercontent.com/1629785/115158469-90cbaf00-a08e-11eb-8fff-fa16115ed6da.png)

![image](https://user-images.githubusercontent.com/1629785/115158527-ddaf8580-a08e-11eb-95dc-5d89c83b7f3d.png)

![image](https://user-images.githubusercontent.com/1629785/115158534-e86a1a80-a08e-11eb-8128-e141662a9f29.png)

**Comment by Tobijudah** [comment]
okay, thanks. On it now

**Comment by abhijit-hota** [comment]
@Tobijudah, I'm sure you'd have thought of something by now but this is a good place to put it according to me. Just suggesting.

![image](https://user-images.githubusercontent.com/8116174/115188832-230d9a80-a103-11eb-836b-869aa1cd312c.png)

**Comment by Tobijudah** [comment]
yeah, I put it there @abhijit-hota. Thanks!

**Comment by JonnyBurger** [comment]
Fixed by #281, thanks again!
