### ISSUE TITLE
Using `yarn create video` installs the project using `npm`

### ISSUE THREAD

**Issue by abhijit-hota** [JonnyBurger/remotion#276]
When I initialize the project using the command `yarn create video` , I expect it to use Yarn as the package manager, using `yarn.lock` file. 

But it still installs all the projects' dependencies using npm and only the `create-video` binary is installed using Yarn.

**Comment by JonnyBurger** [comment]
This is a valid point, I think `yarn create video` can use `yarn` while `npm init video` can use `npm`. We don't have any lockfiles commited anyway in the template. I'll add this to the roadmap!
