### ISSUE TITLE
Audio support

### ISSUE THREAD

**Issue by JonnyBurger** [JonnyBurger/remotion#28]
Right now, the Audio does not get rendered in the output.

Ideally you can add as many <Audio> elements whereever you want, and Remotion will do the composition! Most likely this will use FFMPEG flags to do the composition, but I am not yet 100% sure.

You can subscribe to this issue to follow the progress.

**Comment by nandorojo** [comment]
@JonnyBurger I'm interested in using a youtube video's iFrame in my video. Will it be possible to take the audio from another video and use it here?

**Comment by JonnyBurger** [comment]
@nandorojo I think we can do a youtube video and sync it with the Remotion frame, but the audio seems to be inaccessible because we need to feed it into the ffmpeg command, so for that we need to download it.

Also if we include the YouTube player, we will always have a YouTube watermark which is not so nice.
The best way to achieve this and still stay completely programmatic is to use the `ytdl` CLI application to first download the video, and then use it locally. This will definitely work!

**Comment by nandorojo** [comment]
Got it, downloading it makes much more sense.

**Comment by xavijam** [comment]
It is likely a crazy and non-sense idea, but would it support something like [this](https://github.com/andrewkeig/react-speech)?

**Comment by JonnyBurger** [comment]
@xavijam Not quite, I researched it and there is no way to render an audio generated by `SpeechSynthesis` to an audio tag or to save it. It's a feature that browsers are lacking at the moment.

However, using something like Google [Cloud Speech to Text](https://cloud.google.com/speech-to-text?hl=en), I'm confident it works!

**Comment by xavijam** [comment]
That's fantastic, thank you!

**Comment by JonnyBurger** [comment]
Released in 2.0! 

https://remotion.dev/blog/2-0

**Comment by deeayeen** [comment]
@JonnyBurger is SpeechSynthesis still unusable in Remotion?

**Comment by JonnyBurger** [comment]
@deeayeen It still is.
