### ISSUE TITLE
Warning: Maximum update depth exceeded. This can happen when a component calls setState inside useEffect, but useEffect either doesn't have a dependency array, or one of the dependencies changes on every render.

### ISSUE THREAD

**Issue by sashee** [JonnyBurger/remotion#285]
I'm seeing this error when I run the preview server and open the browser console. It is repeated ~4 times / sec and it clutters the console. I'm using Remotion 2.0.2.

![image](https://user-images.githubusercontent.com/82075/115387111-84546d00-a1da-11eb-8662-c7bb4d5c2af8.png)

**Comment by JonnyBurger** [comment]
Thanks for reporting this!
Looks like a pretty serious issue. I cannot reproduce it, do you have any hints how you get this to happen?

**Comment by JonnyBurger** [comment]
OK managed to reproduce! It happens when I enable rich timeline. Investigating now...
