### ISSUE TITLE
Homepage is not responsive on mobile device

### ISSUE THREAD

**Issue by Iamshankhadeep** [JonnyBurger/remotion#294]
This is a screenshot of homepage on mobile device.
![image](https://user-images.githubusercontent.com/24645773/115510694-ae229800-a29d-11eb-904a-e3bc63405396.jpeg)

**Comment by Tobijudah** [comment]
can hop on this

**Comment by JonnyBurger** [comment]
Awesome, thank you!

**Comment by Tobijudah** [comment]
@Iamshankhadeep can close 👌🏿

**Comment by Iamshankhadeep** [comment]
@Tobijudah thanks.
