### ISSUE TITLE
Handling Color Change Animations

### ISSUE THREAD

**Issue by arindam89** [JonnyBurger/remotion#296]
Hello Jonny,

Thanks for this great tool.

I have a question around handling animations. Mostly, any transform we want to apply should be explicit and tracked in someway via frame, fps, spring, interpolate etc.

But if I have a CSS transition say, color transition from value 1 to value 2, how do we handle this usecase or similar usecases where the property changing is non-numeric in nature.

Here is an example video with Concurrency 8,

https://user-images.githubusercontent.com/341988/115564962-94517700-a2d6-11eb-8cbb-05376cfac2f2.mp4

You can see the flicker as the color is transitioning. Now, with concurrency 1 its seeme little better but still the timing functions are all screwed up in that case.

Let me know what are you plans for cases like this?

**Comment by Iamshankhadeep** [comment]
Hey @arindam89 we do have `interpolateColors()` (available from remotion 2.0.3) to address this issue. read more about `interpolateColors()` [here](https://www.remotion.dev/docs/interpolate-colors).
Do let me know if it solves your issue.

**Comment by arindam89** [comment]
Super fast and super helpful. Thanks a ton @Iamshankhadeep worked like a charm.


https://user-images.githubusercontent.com/341988/115577139-c7e5ce80-a2e1-11eb-8ba9-cf788393f8de.mp4
