### ISSUE TITLE
Add performance tips to docs

### ISSUE THREAD

**Issue by JonnyBurger** [JonnyBurger/remotion#301]
Great advice by @onion2k on Discord:

![image](https://user-images.githubusercontent.com/1629785/115676311-c0f5a500-a34f-11eb-916a-aebee702b1ce.png)

**Comment by Tobijudah** [comment]
hey Jonny. where do you intend this should be added to?

**Comment by JonnyBurger** [comment]
Hey @Tobijudah thanks a lot! I think it's most fitting in the "Techniques" section. You can add a new entry to the sidebar by adding it in the `sidebars.js` file in the docs package.
