### ISSUE TITLE
Audio volume interpolation not working on server renders

### ISSUE THREAD

**Issue by treyhoover** [JonnyBurger/remotion#316]
I've followed [these docs](https://www.remotion.dev/docs/using-audio) to have the audio fade out at the end of the video, but it only works in preview, not when rendered server-side.

**Comment by JonnyBurger** [comment]
Hey @treyhoover! Sorry you're having this problem.

I could imagine two reasons for it:

1. You are using an outdated SSR template that has not been adjusted for audio rendering yet - are you passing `assetsInfo` to `stitchFramesToVideo`? Check the updated example for SSR: https://www.remotion.dev/docs/ssr/

2. You are using a different, incompatible version of FFMPEG on the server - it looks like everything below 4.1 is not working. We have a warning for this in the CLI but in the Node.JS API would also be good probably.

If you believe it's neither of these problems, can you post a code snippet of the problem?

**Comment by treyhoover** [comment]
Thanks for the quick response! 

I was able to get this working in a small example, so there must be some other issue with my code. I'll keep fiddling with it 😄
