### ISSUE TITLE
"Unrecognized option 'buildconf'" When rendering video

### ISSUE THREAD

**Issue by CoderNinja123** [JonnyBurger/remotion#325]
Whenever I try to render a video, I am always getting the following output:

```
Error: Command failed with exit code 1: ffmpeg -buildconf
ffmpeg version N-55702-g920046a Copyright (c) 2000-2013 the FFmpeg developers
  built on Aug 21 2013 18:10:00 with gcc 4.7.3 (GCC)
  configuration: --disable-static --enable-shared --enable-gpl --enable-version3 --disable-w32threads --enable-avisynth --enable-bzlib --enable-fontconfig --enable-frei0r --enable-gnutls --enable-iconv --enable-libass --enable-libbluray --enable-libcaca --enable-libfreetype --enable-libgsm --enable-libilbc --enable-libmodplug --enable-libmp3lame --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenjpeg --enable-libopus --enable-librtmp --enable-libschroedinger --enable-libsoxr --enable-libspeex --enable-libtheora --enable-libtwolame --enable-libvo-aacenc --enable-libvo-amrwbenc --enable-libvorbis --enable-libvpx --enable-libx264 --enable-libxavs --enable-libxvid --enable-zlib
  libavutil      52. 42.100 / 52. 42.100
  libavcodec     55. 29.100 / 55. 29.100
  libavformat    55. 14.101 / 55. 14.101
  libavdevice    55.  3.100 / 55.  3.100
  libavfilter     3. 82.100 /  3. 82.100
  libswscale      2.  5.100 /  2.  5.100
  libswresample   0. 17.103 /  0. 17.103
  libpostproc    52.  3.100 / 52.  3.100
Unrecognized option 'buildconf'.
```

I don't remember how, but the first time I ran it, it installed pupeteer and actually made my video, but consequently I get the same output. I have installed `ffmpeg` and added it to path. It seems to be that the issue lays in passing some CLI parameter called `buildconf`.

Please do help me out with it.

Command I Ran:

`npm run build`

There's some more extra output of the error:

```
Error splitting the argument list: Option not found
    at makeError (Remotion\node_modules\execa\lib\error.js:59:11)
    at handlePromise (Remotion\node_modules\execa\index.js:114:26)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async getFfmpegBuildInfo (Remotion\node_modules\@remotion\renderer\dist\ffmpeg-flags.js:14:18)
    at async Object.getFfmpegVersion (Remotion\node_modules\@remotion\renderer\dist\ffmpeg-flags.js:35:23)    
    at async Object.render (Remotion\node_modules\@remotion\cli\dist\render.js:52:27)
    at async Remotion\node_modules\@remotion\cli\dist\index.js:39:9 {
  shortMessage: 'Command failed with exit code 1: ffmpeg -buildconf',
  command: 'ffmpeg -buildconf',
  exitCode: 1,
  signal: undefined,
  signalDescription: undefined,
  stdout: '',
  stderr: 'ffmpeg version N-55702-g920046a Copyright (c) 2000-2013 the FFmpeg developers\r\n' +
    '  built on Aug 21 2013 18:10:00 with gcc 4.7.3 (GCC)\r\n' +
    '  configuration: --disable-static --enable-shared --enable-gpl --enable-version3 --disable-w32threads --enable-avisynth --enable-bzlib --enable-fontconfig --enable-frei0r --enable-gnutls --enable-iconv --enable-libass --enable-libbluray --enable-libcaca --enable-libfreetype --enable-libgsm 
--enable-libilbc --enable-libmodplug --enable-libmp3lame --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenjpeg --enable-libopus --enable-librtmp --enable-libschroedinger --enable-libsoxr --enable-libspeex --enable-libtheora --enable-libtwolame --enable-libvo-aacenc --enable-libvo-amrwbenc --enable-libvorbis --enable-libvpx --enable-libx264 --enable-libxavs --enable-libxvid --enable-zlib\r\n' +
    '  libavutil      52. 42.100 / 52. 42.100\r\n' +
    '  libavcodec     55. 29.100 / 55. 29.100\r\n' +
    '  libavformat    55. 14.101 / 55. 14.101\r\n' +
    '  libavdevice    55.  3.100 / 55.  3.100\r\n' +
    '  libavfilter     3. 82.100 /  3. 82.100\r\n' +
    '  libswscale      2.  5.100 /  2.  5.100\r\n' +
    '  libswresample   0. 17.103 /  0. 17.103\r\n' +
    '  libpostproc    52.  3.100 / 52.  3.100\r\n' +
    "Unrecognized option 'buildconf'.\r\n" +
    'Error splitting the argument list: Option not found',
  failed: true,
  timedOut: false,
  isCanceled: false,
  killed: false
```

**Comment by CoderNinja123** [comment]
Also note that FFMPEG works all fine when I tried it out with `fluent-ffmpeg` or even did some coversion myself.

**Comment by JonnyBurger** [comment]
Thanks for reporting this issue! It helps us better handle these FFMPEG versions that don't support the `-buildconf` command.

When #235 is merged, no error will be thrown but a non-dismissable warning will appear.
This version is from 2013 and doesn't have all the features Remotion needs. Audio will not work for example.
I suggest to upgrade to a newer version.

**Comment by JonnyBurger** [comment]
Thanks for reporting this issue! It helps us better handle these FFMPEG versions that don't support the `-buildconf` command.

When #235 is merged, no error will be thrown but a non-dismissable warning will appear.
This version is from 2013 and doesn't have all the features Remotion needs. Audio will not work for example.
I suggest to upgrade to a newer version.

**Comment by JonnyBurger** [comment]
Thanks for reporting this issue! It helps us better handle these FFMPEG versions that don't support the `-buildconf` command.

When #235 is merged, no error will be thrown but a non-dismissable warning will appear.
This version is from 2013 and doesn't have all the features Remotion needs. Audio will not work for example.
I suggest to upgrade to a newer version.

**Comment by CoderNinja123** [comment]
So... I have an *outdated* version of FFMPEG? If so, how can I upgrade the version?

P.S. I use Windows, so would `scoop` do the job?

**Comment by JonnyBurger** [comment]
@CoderNinja123 I don't about Scoop, we link to this guide in our docs: https://github.com/adaptlearning/adapt_authoring/wiki/Installing-FFmpeg

I think if you uninstall your current version and follow this one you should be good to go!

**Comment by CoderNinja123** [comment]
Oh. Thanks! Now I am able to render the videos.

Another issue I had was that because of `pip`, there were 2 `ffmpeg.exe` files in the path. If anyone else has a similar problem, run `where ffmpeg` and delete the other files.
