### ISSUE TITLE
[Idea] Preserve the video position after a reload

### ISSUE THREAD

**Issue by sashee** [JonnyBurger/remotion#335]
[<img alt="Issuehunt badges" src="https://img.shields.io/badge/IssueHunt-%240%20Funded-%2300A156.svg" />](https://issuehunt.io/r/JonnyBurger/remotion/issues/335)

I regularly see the hot reload stop working, I suspect if there is a compile error then all later updates are discarded. In these cases I need to do a full browser refresh. This is fast enough, but then the video is reset back to the beginning. It would be great if a refresh would keep the timeline position (for example, it could change the URL hash, similar to youtube).

---

<details>
<summary>
<b>IssueHunt Summary</b>
</summary>

### Tips

- Checkout the [Issuehunt explorer](https://issuehunt.io/r/JonnyBurger/remotion/) to discover more funded issues.
- Need some help from other developers? [Add your repositories](https://issuehunt.io/r/new) on IssueHunt to raise funds.
</details>

**Comment by JonnyBurger** [comment]
Great idea! Putting this on the roadmap, I think this one can be implemented in just a few line of code, so I see a high chance of this being implemented soon :) I think I prefer localStorage though, as most settings are stored there already.
