### ISSUE TITLE
Using Web Audio API

### ISSUE THREAD

**Issue by zackradisic** [JonnyBurger/remotion#34]
Hi, I would like to use this project alongside the web audio API to create audio visualizations. Before I start trying to implement this, are there any caveats or nuances that would prevent it from being possible?

**Comment by JonnyBurger** [comment]
Hi @zackradisic!

The biggest limitation I think right now is that audio is not being rendered at the moment. You can see the current status here: https://www.remotion.dev/docs/audio/

And you can subscribe to #28 to get updates on the progress.

That being said, you should still be able to render the visuals! I don't see why not. For the moment you just have to add the audio afterwards in another way.

**Comment by tomByrer** [comment]
Actually, it would be neat if a separate but compatible tool would be built to compose audio.  It could use timecodes from WebVTT or some other captions standard to help edit & add multiple audio sources.

I'm not sure how the audio & video get stitched together; I've done video-first then audio overlays (Ableton Live) & audio-first then video graphics.  But an audio-only composing would be helpful, so might as well program separately.

**Comment by JonnyBurger** [comment]
Implemented now! https://www.remotion.dev/docs/audio-visualization

**Comment by JonnyBurger** [comment]
Our new `<Audio>` tag uses the Web Audio API: https://www.remotion.dev/docs/media/audio
