### ISSUE TITLE
Player - doesn’t work in NextJS

### ISSUE THREAD

**Issue by JonnyBurger** [JonnyBurger/remotion#352]

**Comment by larskarbo** [comment]
The player works in NextJS, but not the audio.

Only occurs when building and serving. Dev server is fine.

**Comment by JonnyBurger** [comment]
@larskarbo

Hi Lars!
I'll investigate it. Can you give me some info (if necessary over DM) what audio you are trying to import and from where? With which tool are you serving the static site?

We've just found that some static hosts don't support the `Range` HTTP header, making it impossible to play audio not from the start: #402 therefore I am asking about this since it potentially can be a cause.

**Comment by larskarbo** [comment]
Thanks, of course!

We're building a simple video editor for Personate. I made a Remotion video quickly here: https://personate.ai/studio/0fac6ojc6ljky.

The images work great.

Audio doesn't work. The audios are a bunch of these: https://server.personate.ai/tempaudio/qz8fh18pdfe1zds8u51y.mp3 (voice) and https://server.personate.ai/bensound-creativeminds.mp3 (background music track).

All the audio files is served with an express server. (nothing to do with nextjs).

Happy to help you debug this issue! We are planning on launching our thing in a few days 🙌

**Comment by JonnyBurger** [comment]
@larskarbo Wow so cool!
I've already figured out the issue but happy to chat if you want to tell more!

The problem is that Next.JS sets process.env.NODE_ENV === 'production', so Remotion thinks it's in rendering mode. Will probably land a fix later today!

**Comment by larskarbo** [comment]
Awesome! Appreciate it 🙌

**Comment by CryogenicPlanet** [comment]
Hey I can't seem to even get the example for the player from the docs to run on `next` using the alpha packages

Here is the link to the codesanbox https://codesandbox.io/s/suspicious-mclean-m2oon?file=/pages/index.tsx
https://m2oon.sse.codesandbox.io/

```
 "dependencies": {
    "@headlessui/react": "^1.0.0",
    "@heroicons/react": "^1.0.1",
    "@remotion/player": "2.2.0-alpha.ddf867ea",
    "autoprefixer": "^10.2.4",
    "color-namer": "^1.4.0",
    "next": "latest",
    "polished": "^4.1.3",
    "postcss": "^8.2.4",
    "react": "^17.0.1",
    "react-dom": "^16.12.0",
    "remotion": "2.2.0-alpha.ddf867ea",
    "tailwindcss": "^2.0.2"
  }
```

**Comment by JonnyBurger** [comment]
@CryogenicPlanet You hit an internal React error because of an error mismatch. I upgraded both `react` and `react-dom` to 17.0.2 and the error went away!
