### ISSUE TITLE
Allow Player to fit parent (resize player to fit container)

### ISSUE THREAD

**Issue by kode-ninja** [JonnyBurger/remotion#365]
It'll be awesome to be able to resize `@remotion/player` - specifically to fit it's parent size

**Comment by JonnyBurger** [comment]
@kode-ninja does adding `style={{width: '100%'}}` to the player component work for you?

We plan on documenting this for the final version of the player.

**Comment by kode-ninja** [comment]
yes, it works!

**Comment by JonnyBurger** [comment]
OK, that's great! 😊 

Gonna close this issue, if you find other problems regarding this, feel free to report it!
