### ISSUE TITLE
Remotion asset are stored using path name, making it hard for speech synthesis api

### ISSUE THREAD

**Issue by sheunglaili** [JonnyBurger/remotion#371]
I was playing with remotion with text-to-speech api recently. I came with with issue that when fetching assets from remote url, the path of the resource are being used as the file name. For example: when I call to `/speech?text=hello world`, remotion store it in file called `/var/folders/23/p6hvrd8s1416bf736mrlqkx80000gn/T/react-motion-graphicstwQAss/speech` which makes it unidentifiable by remotion when I am synthesis speech for different sentence in a video.

Currently, I am working around this by altering the endpoint into `/speech/:text` but this won't help if I have a longer sentence because it's going to create a file with super long name.

I'd suggest hashing the entire URL as the file name. Any thoughts ?

**Comment by JonnyBurger** [comment]
Thanks for the report, this is indeed a bug and a valid idea! Putting it on the roadmap.

**Comment by sheunglaili** [comment]
I've created a PR for this issue. https://github.com/JonnyBurger/remotion/pull/373
