### ISSUE TITLE
No such file or directory - possible race condition?

### ISSUE THREAD

**Issue by natasha-93** [JonnyBurger/remotion#384]
We're seeing an intermittent error where ffprobe appears to be attempting to process a file that hasn't finished downloading yet: 

```
Job failed Command failed with exit code 1: ffprobe -v error -show_entries stream=channels -of default=nw=1 /tmp/react-motion-graphics9lLWlV/v0blista-video-app.appspot.comomusic%2FInspiration.mp3

/tmp/react-motion-graphics9lLWlV/v0blista-video-app.appspot.comomusic%2FInspiration.mp3: No such file or directory
```

Rerunning the build usually resolves the issue (this seems to be happening about 20% of the time).

**Comment by Iamshankhadeep** [comment]
what is the version of `remotion` you are using?

**Comment by natasha-93** [comment]
Currently running 2.1.2

**Comment by Iamshankhadeep** [comment]
okay, can you do one thing? can you upload the code to Github so that we can debug.

**Comment by JonnyBurger** [comment]
I think I found out what might be causing it:

We are using [`stream.pipeline`](https://nodejs.org/api/stream.html#stream_stream_pipeline_streams_callback) from Node.JS and waiting for it's callback. The changelog of Node.JS says:

`14.0.0 - The pipeline(..., cb) will wait for the 'close' event before invoking the callback. The implementation tries to detect legacy streams and only apply this behavior to streams which are expected to emit 'close'.`

This leads me to think they fixed a bug in v14 where the callback would get called prematurely and the file was not yet fully written to disk! Ideally you can confirm that you have a Node version below v14 to give us more confidence that this is indeed the problem :) Fix coming soon.

**Comment by natasha-93** [comment]
Node v15.5.1 so that's not it unfortunately.

**Comment by JonnyBurger** [comment]
@natasha-93 Ah, bummer! I am reopening it, but can you nonetheless try out v2.1.4 and see if it's fixed? Since we rewrote the whole statement, there might still be a chance.

**Comment by natasha-93** [comment]
v2.1.4 seems to have fixed it - thanks!
