### ISSUE TITLE
H.265 videos aren't rendering (white screen)

### ISSUE THREAD

**Issue by treyhoover** [JonnyBurger/remotion#387]
ffmpeg appears to be setup to support h.265 encodings, but they're just rendering as solid white backgrounds:

```
ffmpeg version 4.4 Copyright (c) 2000-2021 the FFmpeg developers
built with Apple clang version 12.0.0 (clang-1200.0.32.29)
configuration: --prefix=/usr/local/Cellar/ffmpeg/4.4 --enable-shared --enable-pthreads --enable-version3 --enable-avresample --cc=clang --host-cflags= --host-ldflags= --enable-ffplay --enable-gnutls --enable-gpl --enable-libaom --enable-libbluray --enable-libdav1d --enable-libmp3lame --enable-libopus --enable-librav1e --enable-librubberband --enable-libsnappy --enable-libsrt --enable-libtesseract --enable-libtheora --enable-libvidstab --enable-libvorbis --enable-libvpx --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxml2 --enable-libxvid --enable-lzma --enable-libfontconfig --enable-libfreetype --enable-frei0r --enable-libass --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenjpeg --enable-libspeex --enable-libsoxr --enable-libzmq --enable-libzimg --disable-libjack --disable-indev=jack --enable-videotoolbox
libavutil      56. 70.100 / 56. 70.100
libavcodec     58.134.100 / 58.134.100
libavformat    58. 76.100 / 58. 76.100
libavdevice    58. 13.100 / 58. 13.100
libavfilter     7.110.100 /  7.110.100
libavresample   4.  0.  0 /  4.  0.  0
libswscale      5.  9.100 /  5.  9.100
libswresample   3.  9.100 /  3.  9.100
libpostproc    55.  9.100 / 55.  9.100
```

I'm just seeing this behavior on videos from my iPhone 12. As a workaround, changing my camera settings to use the "most compatible" format i.e. h264 seems to resolve the white screen issue, but I'm wondering if this is a problem with my instance of ffmpeg or remotion itself.

**Comment by Iamshankhadeep** [comment]
@treyhoover is h.265 videos working on the preview? which os are you using?

**Comment by treyhoover** [comment]
Good question. They don't appear to be working on preview either. I'm on macOS Big Sur 11.0.1.

**Comment by Iamshankhadeep** [comment]
@treyhoover I see so chrome does not have HEVC (h.265) support yet, and we use chrome or chromium for rendering that's why you are getting blank video. best is to use h.264 or webm videos

**Comment by JonnyBurger** [comment]
Indeed, Chrome doesn't support playing H265 videos because it doesn't include the codec.

Our support for H265 concerns encoding, so you can output a video in HEVC format.
Importing it however, doesn't work and we cannot do much about it because it's a browser constraint.

So I'll close the issue, however still with an open ear if you think there's something we can do on our side about this. I would suggest converting the video first to H264 before importing it.
