### ISSUE TITLE
Preload audio in player

### ISSUE THREAD

**Issue by larskarbo** [JonnyBurger/remotion#409]
Is there any way to preload the audio in the player?

Right now the user misses the first second of audio when playing the video

**Comment by JonnyBurger** [comment]
I guess the conventional APIs of the Web for Preloading apply:

- Add the `preload` attribute to the <Audio> tag, it will be passed through
- If you want to be sure that the user will not miss a beat, load it outside the player, and only mount the player once the audio has been loaded, or block playback for example by not showing any controls

**Comment by JonnyBurger** [comment]
I hope the answer is satisfactory! Closing the issue, if there are further questions, you know what to do.
