### ISSUE TITLE
SASS as default

### ISSUE THREAD

**Issue by samdoeswork** [JonnyBurger/remotion#438]
Hi,
I really like Remotion. Thank you for this project !

I actually learned React just to use this library. (Coming from mostly Angular, some Vue/Svelte).

I tried following the docs to extend the webpack config to support SASS - but ended up with a ton of issues related to dependency version conflicts (I'm quite familiar with webpack etc.)

Is there a reason not to support SASS by default given how widely used/useful it is? Seems like a sensible default for a modern project.

**Comment by JonnyBurger** [comment]
Hi @samdoeswork! Thanks a lot for the kind words!

Sorry for the trouble with the docs for getting SASS / SCSS to work. I have just tried it myself and opened a PR to improve the docs: #440 

We try to keep Remotion as modular as possible to keep it lightweight and reduce our maintenance burden. While I agree SASS is very popular, it also competes with LESS and CSS-in-JS solutions, so we don't want to take any opinion on it. I hope the updated docs will make it very easy to get SASS running though!
