### ISSUE TITLE
Incorrect wording in license document

### ISSUE THREAD

**Issue by joepie91** [JonnyBurger/remotion#47]
The [license document](https://github.com/JonnyBurger/remotion/blob/main/LICENSE.md) says:

>  This two-tier system was designed to ensure funding for this project while still allowing it to be open source.

However, this is incorrect; the license conditions violate points 3 and 5 of the [Open-Source Definition](https://opensource.org/osd-annotated), and therefore it cannot be called open-source. Something being open-source is about more than just being able to look at the source code, and so several additional requirements around usage rights and non-discrimination apply.

The common term for the sort of license used for this project is a "source-available license", though "while still allowing the source code to be publicly readable" would probably be easier to read and understand :)

Relatedly, the following [from the website](https://www.remotion.dev/docs/license) is also not entirely right:

> Unlike many open source projects, it is not allowed to clone or fork Remotions code for the purpose of creating a competitor.

You can just leave out "many" here - people being allowed to fork and/or create a 'competitor' is inherently allowed by an open-source license. If that is not allowed, then it wouldn't qualify as open-source.

Those seem to be the only two places I've found; everything else I've looked at seems fine to me, wording-wise.

**Comment by JonnyBurger** [comment]
Thanks for reviewing! See the PR #58 for my response 👍
