### ISSUE TITLE
GIFs are action weird

### ISSUE THREAD

**Issue by Utkarshbhimte** [JonnyBurger/remotion#51]
I am adding GIF to an img tag, it looks normal in the dev preview but on build it seems to flicker
I have configured the Composition to be in 60 FPS

https://user-images.githubusercontent.com/13379773/107623372-3d4c7780-6c7f-11eb-96b8-045864f035b7.mp4

I am using windows WSL with node v14

**Comment by JonnyBurger** [comment]
Thanks for the report! I could imagine two causes:

- Is it an animated GIF? That's not supported directly, but you could convert it to a video and [sync it with the timeline](https://www.remotion.dev/docs/video/).
- Is it a static GIF from a remote location? The flicker could be fixed if you use the new [`<Img/>` component](https://www.remotion.dev/docs/img).


If it's neither of those, please post a code example!

**Comment by JonnyBurger** [comment]
I'm marking it as closed because no response and I assume it's one of the reasons above, feel free to reopen it if it needs taking a closer look.
