### ISSUE TITLE
Support for JSX (not TSX)

### ISSUE THREAD

**Issue by tomisu** [JonnyBurger/remotion#52]
I love this project, but I find typescript cumbersome to work with.

Would it be possible to a default setting for disabling TS?

I'd love it.

**Comment by JonnyBurger** [comment]
Sounds good, @pomber also wanted this. Should be a relatively easy Webpack tweak, expect this to land soon 👍

**Comment by Iamshankhadeep** [comment]
@JonnyBurger assign this task to me. I'll work on it.
