### ISSUE TITLE
Truncate repository

### ISSUE THREAD

**Issue by JonnyBurger** [JonnyBurger/remotion#57]
The repository is quite big and takes a long time to clone. That's because there were media files that are now deleted. Need to find a way to somehow purge them so the repo is lightweight.

**Comment by pluma** [comment]
I think this is what you're thinking of? https://docs.github.com/en/github/managing-large-files/removing-files-from-a-repositorys-history

**Comment by lucaspelloni2** [comment]
I would rather use https://docs.github.com/en/github/authenticating-to-github/removing-sensitive-data-from-a-repository

**Comment by JonnyBurger** [comment]
I went with the sensitive data tutorial from @lucaspelloni2!

Thanks a lot for the help 💙 The repo is now much more lightweight

**Comment by lucaspelloni2** [comment]
<3
