### ISSUE TITLE
WSL npm start error

### ISSUE THREAD

**Issue by letoribo** [JonnyBurger/remotion#61]
[
![start-error](https://user-images.githubusercontent.com/4941581/107667138-f5861a00-6c97-11eb-8a1b-5b731d4263d6.PNG)
](url)

**Comment by JonnyBurger** [comment]
We don't directly invoke Powershell, could it be this issue? https://github.com/expo/expo-cli/issues/2617#issuecomment-700630128

**Comment by letoribo** [comment]
I saw it yesterday too, but it didn't help

**Comment by yuta0801** [comment]
It's probably this issue of `open` dependency of `better-opn` used for open browser. https://github.com/sindresorhus/open/issues/218

At the moment, we can set `BROWSER` env to `none` like `BROWSER=none npm start` to prevent execute that and open browser manually.

**Comment by letoribo** [comment]
but WSL version isn't 2
[
![WSL-v](https://user-images.githubusercontent.com/4941581/107835097-04a4bf00-6da1-11eb-94e2-626e4b90a883.PNG)
](url)

**Comment by arengoh** [comment]
Try change the browser

**Comment by letoribo** [comment]
[
![npm start](https://user-images.githubusercontent.com/4941581/107835400-0b800180-6da2-11eb-83c7-c147134051c0.PNG)
](url)

**Comment by JonnyBurger** [comment]
Thanks for tracking the bug down! 💙  I upgraded the dependency.
I will release 1.3.0 tomorrow morning - if the problem persists, let me know.
