### ISSUE TITLE
npm run build didn't work on windows

### ISSUE THREAD

**Issue by mahmoodfathy** [JonnyBurger/remotion#67]
hey there when i ran npm run build after installing ffmpeg as advised by the console log , it didn't want to render my video as well despite having ffmpeg appear when i run ffmpeg -version , so after some digging in the code base i found out that it checks for the ffmpeg module with the where command which can only be ran inside  C:\Windows\system32 , so to work around this if anybody is facing the same problem is to set an environment variable which includes this folder, another way is>

1- Go to your pc desktop icon , hit right click and properties
2-on the left hit the Advanced system settings
3-go to Advanced on the bottom environment variables
4-search for the Path environment variable , hit edit and browse to the folder mentioned above in c>>windows>system32 hit ok two time
5-restart your terminal and run the command npm run build command again and voila it works

This should be a seemless process on windows as well , i suggest adding such message to the user to include his environment variable in the console log or by handling it differently in your code , Hope this helps somebody as well

**Comment by JonnyBurger** [comment]
Hey @mahmoodfathy thanks a lot for the instructions! The same happened to me. I just opened #98 to hopefully improve the error message by a lot.
The steps are not exactly as you described, I am running on Windows 10, hope that everything is correct.

Thanks for the great contribution! 💙

**Comment by mahmoodfathy** [comment]
@JonnyBurger  Nice , i just read the commits looks great with detailed explanations , the messages do the same thing yes as here , it's just a different way around it , <3 ,  Thanks
