### ISSUE TITLE
Occasional crash "Session closed. Most likely the page has been closed"

### ISSUE THREAD

**Issue by JonnyBurger** [JonnyBurger/remotion#69]
I occasionally get the error from Puppeteer "Session closed. Most likely the page has been closed", especially when heavily multithreading. Wondering if it can be fixed by upgrading puppeteer, retrying etc.

**Comment by mahmoodfathy** [comment]
@JonnyBurger  it's actually erroring that puppeteer can't take a screen shot after some time during building my video , this error happened when my video got slightly bigger , i don't know why , the bundling renders the first 15% only
![faliure](https://user-images.githubusercontent.com/71036818/107828012-9952f100-6d90-11eb-8c74-4423e192fc11.JPG)

**Comment by mahmoodfathy** [comment]
@JonnyBurger  After some further investigation turns out this error due to the Img component in remotion , it kept not bundling and failing to screenshot cause of that component when i changed it to a normal img tag it worked as expected , dont know why tho it's pretty weird

**Comment by JonnyBurger** [comment]
Very interesting, don't know why it could be, but I use it as a pointer in my investigation! Thank you!

**Comment by mahmoodfathy** [comment]
when i used it in my development it appeared normally in the video , but kept failing the video rendering , i suspect that it didn't load so puppeteer couldn't  take a screenshot of the image

**Comment by JonnyBurger** [comment]
After upgrading Puppeteer, the error is gone!
Will be fixed in the next release. You can try the newest alpha on NPM `1.3.0-alpha.39ecd4ef` (Upgrade `remotion`, `@remotion/bundler`, `@remotion/cli`, `@remotion/eslint-config`, `@remotion/renderer`)
