### ISSUE TITLE
PNG output - zero-pad output indices

### ISSUE THREAD

**Issue by zackdotcomputer** [JonnyBurger/remotion#89]
## Issue:

Because the render `--png` mode outputs images without leading zero-padding, `ls` outputs them in the wrong order (using alphabetical rather than numerically aware order). This means that using ImgMagick to convert them into a gif fails because the frames are out of order.

## Fix:

The indices should be padded with leading zeroes so that ls -a of the output folder is in frame order.

**Comment by zackdotcomputer** [comment]
Ah - I think I get it - you're using the %d selector in ffmpeg's `-i` flag to tell it to use numeric sort for that... I wonder if ImageMagick (which I'm using to compile the pngs into a gif) can do the same...

**Comment by JonnyBurger** [comment]
We will also fix it on Remotions side 👍

**Comment by zackdotcomputer** [comment]
Ha well... since you wrote this in TS and I know that well enough to dive in and make a mess of things, I did take a quick stab at it. I'll PR my draft over and you can use or ignore it as you wish. 👍
