### ISSUE TITLE
Allowing to edit Webpack config

### ISSUE THREAD

**Issue by pomber** [JonnyBurger/remotion#9]
First, congrats on the launch, this project is amazing.

I was wondering if there is any hook or any plan to let the user extend the webpack config. I'm particularly interested in importing markdown/mdx files.

Thanks!

**Comment by JonnyBurger** [comment]
Seems to make sense to allow people to customize the Webpack Config, this is not the only request for this: https://twitter.com/HamedMamdoohii/status/1358834914993569799

I'll consider this feature!

**Comment by nico-martin** [comment]
I guess it would be possible to allow custom configuration to be injected here, right?
https://github.com/JonnyBurger/remotion/blob/main/packages/bundler/src/webpack-config.ts

We could create a cutsom webpack config for plugins and loaders in the project root that will be parsed and injected.

**Comment by JonnyBurger** [comment]
Work in progress: https://github.com/JonnyBurger/remotion/pull/30
